version: 0.1

phases:
  build:
    commands:
      - echo Build completed on `date`
      - mvn clean install

artifacts:
  files:
    - target/frontservice-0.0.1-SNAPSHOT.jar
    - Dockerfile